name: liquid_engine
description: A dart port of the liquid / django HTML template engine.
version: 0.2.2
homepage: https://github.com/ergonlabs/liquid_dart

environment:
  sdk: '>=3.0.0 <=3.2.0'

dependencies:
  string_scanner: ^1.1.0
  gato: ^0.0.5+1
  more: 4.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.17.7
