name: liquid_engine
description: A dart port of the liquid / django HTML template engine.
version: 1.0.0
homepage: https://github.com/ergonlabs/liquid_dart
author: stefanrusek <stefan@rusek.org>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  string_scanner: ^1.0.5

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.16.8
